import <std.io>;

fn main(): int {
    let a: *int = array::new(8);
    array::push(a, 10);
    array::push(a, 20);
    array::push(a, 30);
    let n: int = array::len(a);
    io::print(n);
    io::print("\n");
    let v: int = array::get(a, 1);
    io::print(v);
    io::print("\n");
    let top: int = array::pop(a);
    io::print(top);
    io::print("\n");
    io::print(array::len(a));
    io::print("\n");
    array::free(a);
    io::print("array ok\n");
    return 0;
}
