import <std.io>;
class Counter {
    value: int;
    step: int;

    fn new(self, v: int, s: int) {
        self.value = v;
        self.step = s;
    }

    fn tick(self) {
        self.value = self.value + self.step;
    }

    fn get(self): int {
        return self.value;
    }
}

fn main(): int {
    let c = Counter { value: 0, step: 2 };
    c.tick();
    c.tick();
    c.tick();
    io::print(c.get());
    return 0;
}
