export module; 
import <std.io>
import <std.string>

external unit sayHi(nama: str) {
  print("halo %{nama}!\n);
}

class User {
  private {
  mut hp: 100;
  mut power: 10;
  }
  public {
  mut name: str;
  
  fn setName(nama: str) {
  return this.name = nama;
  }
  
  fn set(type: str, val: str) {
  if (type == "hp" || type == "Hp") {
  return this.hp = val;
  }
  else if (type == "power" || type == "Power") {
  return this.power = val;
  }
  }
}

fn main(argc: str, *argv[]: str): int {
  print("Masukan nama anda: ");
  let nama: str = input();
  
  sayHi(nama);
  
  let user1: User = User { name: nama };
  
  
  
}