#ifndef TOKEN_H
#define TOKEN_H
typedef enum {
    TOK_INT_LIT, TOK_FLOAT_LIT, TOK_DOUBLE_LIT, TOK_LONG_LIT,
    TOK_STRING_LIT, TOK_CHAR_LIT, TOK_BOOL_LIT,
    TOK_BYTE, TOK_SHORT, TOK_USHORT, TOK_INT, TOK_UINT,
    TOK_LONG, TOK_ULONG, TOK_FLOAT, TOK_DOUBLE, TOK_BOOL, TOK_STR, TOK_CHAR,
    TOK_LET, TOK_MUT, TOK_CONST, TOK_FN, TOK_UNIT, TOK_RETURN,
    TOK_IF, TOK_ELSE, TOK_WHILE, TOK_DO, TOK_FOR, TOK_MATCH,
    TOK_IMPORT, TOK_EXPORT, TOK_MODULE, TOK_STRUCT, TOK_ENUM, TOK_CLASS, TOK_PUBLIC, TOK_PRIVATE,
    TOK_THIS, TOK_NEW, TOK_TRUE, TOK_FALSE, TOK_IN, TOK_REGION, TOK_BREAK, TOK_CONTINUE,
    TOK_TYPE, TOK_DEFER, TOK_EXTERNAL, TOK_UNSAFE, TOK_NULL,
    TOK_AT, TOK_COMPTIME,
    TOK_IDENT,
    TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT, TOK_AMP,
    TOK_PIPE, TOK_CARET, TOK_TILDE,
    TOK_ASSIGN, TOK_EQ, TOK_NEQ, TOK_LT, TOK_GT, TOK_LTE, TOK_GTE,
    TOK_AND, TOK_OR, TOK_NOT, TOK_ARROW, TOK_FAT_ARROW,
    TOK_PLUS_ASSIGN, TOK_MINUS_ASSIGN, TOK_STAR_ASSIGN, TOK_SLASH_ASSIGN,
    TOK_PERCENT_ASSIGN, TOK_AMP_ASSIGN, TOK_PIPE_ASSIGN, TOK_CARET_ASSIGN,
    TOK_SHL, TOK_SHR, TOK_SHL_ASSIGN, TOK_SHR_ASSIGN,
    TOK_INC, TOK_DEC, TOK_COLON, TOK_DOUBLE_COLON, TOK_SEMICOLON, TOK_COMMA, TOK_DOT,
    TOK_RANGE, TOK_RANGE_EQ,
    TOK_QUESTION, TOK_HASH, TOK_AS,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE, TOK_LBRACKET, TOK_RBRACKET,
    TOK_INTERP_START,
    TOK_EOF, TOK_UNKNOWN,
} TokenType;

typedef struct {
    TokenType type;
    char *value;
    int line, col;
} Token;

const char *token_type_str(TokenType t);
void token_print(Token *t);
#endif
